export const Experiences = [
  {
    year: "2023 - Present",
    role: "Computer Science Undergraduate",
    Institution: "IIT(Uow)",
    description: "",
    tecnologies: ["Python", "Java", "HTML", "CSS", "Javascript"],
  },
  {
    year: "2023 - Present",
    role: "Frontend Developer",
    Institution: "Freelance",
    description: "",
    tecnologies: [
      "Javascript",
      "CSS",
      "HTML",
      "SCSS",
      "React",
      "Vite",
      "Nextjs",
      "Typescript",
      "Tailwindcss",
      "GSAP",
    ],
  },
  {
    year: "2021 - Present",
    role: "Python Developer",
    Institution: "Open Source",
    description: "",
    tecnologies: ["Python", "MariaDB"],
  },
  {
    year: "2019 - 2022",
    role: "GCE AL's",
    Institution: "Bandaranayake College",
    description: "",
    tecnologies: ["Python", "Arduino", "SQL", "HTML", "CSS"],
  },
];
